apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-app-1
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: talhamoinuddin/my-app-1
    backstage.io/techdocs-ref: dir:.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: talhamoinuddin@github.com
  lifecycle: experimental
